apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "ecommerce-mini.fullname" . }}

  labels:
    {{- include "ecommerce-mini.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "ecommerce-mini.selectorLabels" . | nindent 6 }}

  template:

    metadata:
      labels:
        {{- include "ecommerce-mini.selectorLabels" . | nindent 8 }}

    spec:

      containers:
        - name: ecommerce-mini

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: IfNotPresent

          ports:
          - containerPort: {{ .Values.containerPort }}
